//Let application choose a random free port for quarkus
#quarkus.http.port=0

//setup Twilio config
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.from-number=${TWILIO_FROM_NUMBER}

mp.jwt.verify.issuer=boolean-broker
smallrye.jwt.sign.key-location=jwt-secret.key
smallrye.jwt.sign.algorithm=HS256

security.bcrypt.cost=10

# -------------------------
# Datasource configuration
# -------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres.doidttbevfpsjcssvefr
quarkus.datasource.password=${POSTGRESQL_PWD}
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=prefer&sslfactory=org.postgresql.ssl.NonValidatingFactory
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=5
#Time for which a request will wait for a connection
quarkus.datasource.jdbc.acquisition-timeout=30S
# Max time a connection can stay idle
quarkus.datasource.jdbc.idle-removal-interval=60S
# Max lifetime of a connection
quarkus.datasource.jdbc.max-lifetime=10M